spring:
  jpa:
    show-sql: false
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: update

  datasource:
    driver_class_name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/kafka_demo_hotels"
    username: "kafkaDemo"
    password: "kafkaDemoPass55"

