version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  producer:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: "bash -c 'echo \"Hello, Kafka\" | kafka-console-producer --broker-list kafka:9092 --topic test'"

  consumer:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: "kafka-console-consumer --bootstrap-server kafka:9092 --topic test --from-beginning"
